server:
  port: 8080
  error:
    include-message: always
  ssl:
    enabled: false

origins: ${GATEWAY_URL}
permit-all: /public/**

spring:
  application:
    name: ${CALCULATOR_SERVICE_NAME}

eureka:
  instance:
    hostname: ${CALCULATOR_SERVICE_NAME}
  client:
    region: default
    registry-fetch-interval-seconds: 30