server:
  port: ${DISCOVERY_PORT}

spring:
  application:
    name: ${DISCOVERY_NAME}

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_URL}