server:
  port: ${DISCOVERY_PORT}

origins: ${GATEWAY_URL}
permit-all: /public/**

spring:
  application:
    name: ${DISCOVERY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER}

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_URL}