server:
  port: ${DISCOVERY_PORT}

origins: ${GATEWAY_URL}
permit-all: /actuator/**

spring:
  application:
    name: ${DISCOVERY_NAME}
  security:
    user:
      name: ${DISCOVERY_USER}
      password: ${DISCOVERY_PASSWORD}

eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${DISCOVERY_URL}