server:
  port: ${FODD_SERVICE_PORT}

spring:
  application:
    name: ${FODD_SERVICE_NAME}
  datasource:
    url: ${FOOD_SPRING_DATASOURCE_URL}
    username: ${FOOD_DB_NAME}
    password: ${FOOD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30