server:
  port: ${FOOD_SERVICE_PORT}
  error:
    include-message: always
  ssl:
    enabled: false

origins: ${GATEWAY_URL}
permit-all: /public/**

spring:
  application:
    name: ${FOOD_SERVICE_NAME}
  datasource:
    url: ${FOOD_SPRING_DATASOURCE_URL}
    username: ${FOOD_DB_USER}
    password: ${FOOD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_INTERNAL_ISSUER}
          jwk-set-uri: ${KC_EXTERNAL_ISSUER}

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30