
food-url: lb://${FOOD_SERVICE_NAME}
food-prefix: /api/v1/food

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${GATEWAY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Keycloak
        - id: authorization-server
          uri: ${KC_HOSTNAME_URL}
          predicates:
            - Path=${KC_HTTP_RELATIVE_PATH}/**

        # Food Service
        - id: food-service
          uri: ${food-url}
          predicates:
            - Path=${food-prefix}/**

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30