scheme: http
hostname: gateway
reverse-proxy-port: ${GATEWAY_PORT}
authorization-server-port: ${KEYCLOAK_PORT}
authorization-server-prefix: ${KC_HTTP_RELATIVE_PATH}
authorization-server-uri: ${KC_HOSTNAME_URL}
admin-authorization-server-uri: ${KC_HOSTNAME_ADMIN_URL}
admin-authorization-server-prefix: ${KC_HTTP_ADMIN_RELATIVE_PATH}
bff-port: ${BFF_PORT}
bff-prefix: /bff
bff-uri: ${scheme}://${hostname}:${bff-port}
server:
  port: ${reverse-proxy-port}

spring:
  application:
    name: ${GATEWAY_NAME}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Authorization-server
        - id: authorization-server
          uri: ${authorization-server-uri}
          predicates:
            - Path=${authorization-server-prefix}/**

        - id: admin-authorization-server
          uri: ${admin-authorization-server-uri}
          redicates:
            - Path=${admin-authorization-server-prefix}/**

        # BFF
        - id: bff
          uri: ${bff-uri}
          predicates:
            - Path=${bff-prefix}/**
          filters:
            - StripPrefix=1

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30