
food-url: lb://${FOOD_SERVICE_NAME}
food-prefix: /api/v1/food

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: ${GATEWAY_NAME}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Keycloak
        - id: keycloak
          uri: ${KC_BACKEND_URL}
          predicates:
            - Path=/t/**
          filters:
            - RewritePath=${KC_HTTP_RELATIVE_PATH}/(?<segment>.*), /$\{segment}
            
        # Keycloak Admin
        - id: keycloak-admin
          uri: ${KC_ADMIN_URL}
          predicates:
            - Path=/a/**
          filters:
            - RewritePath=${KC_HTTP_ADMIN_RELATIVE_PATH}/(?<segment>.*), /$\{segment}

        # Food Service
        - id: food-service
          uri: ${food-url}
          predicates:
            - Path=${food-prefix}/**

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30