scheme: http
hostname: gateway
reverse-proxy-port: ${GATEWAY_PORT}
authorization-server-port: ${KEYCLOAK_PORT}
authorization-server-prefix: ${KC_HTTP_RELATIVE_PATH}
authorization-server-uri: ${KC_HOSTNAME_URL}
admin-authorization-server-uri: ${KC_HOSTNAME_ADMIN_URL}
admin-authorization-server-prefix: ${KC_HTTP_ADMIN_RELATIVE_PATH}
food-url: lb://${FOOD_SERVICE_NAME}
food-prefix: /api/v1/food
server:
  port: ${reverse-proxy-port}

spring:
  application:
    name: ${GATEWAY_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Keycloak
        - id: authorization-server
          uri: ${authorization-server-uri}
          predicates:
            - Path=${authorization-server-prefix}/**

        # Food Service
        - id: food-service
          uri: ${food-url}
          predicates:
            - Path=${food-prefix}/**

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 30