food-url: lb://${FOOD_SERVICE_NAME}
food-prefix: /api/v1/food

calculator-url: lb://${CALCULATOR_SERVICE_NAME}
calculator-prefix: /api/v1/calculator

server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: 'pkcs12'
    key-store: 'file:/etc/tls/domain-tls.p12'
    key-store-password: ${TLS_PASSWORD}

spring:
  application:
    name: ${GATEWAY_NAME}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Keycloak
        - id: keycloak
          uri: ${KC_BACKEND_URL}
          predicates:
            - Path=${KC_HTTP_RELATIVE_PATH}/**
          filters:
            - RewritePath=${KC_HTTP_RELATIVE_PATH}/(?<segment>.*), /$\{segment}

        # Food Service
        - id: food-service
          uri: ${food-url}
          predicates:
            - Path=${food-prefix}/**
        
        # Calculator Service
        - id: calculator-service
          uri: ${calculator-url}
          predicates:
            - Path=${calculator-prefix}/**

eureka:
  instance:
    hostname: ${GATEWAY_NAME}
  client:
    region: default
    registry-fetch-interval-seconds: 30